# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentOnProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentOnProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=200)),
                ('goal_description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.CharField(max_length=500)),
                ('cover_pic_url', models.CharField(max_length=250)),
                ('status', models.IntegerField()),
                ('confidentiality', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karma.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('goals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TagGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Goal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Project'),
        ),
        migrations.AddField(
            model_name='commentonproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Project'),
        ),
        migrations.AddField(
            model_name='commentonprogress',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Progress'),
        ),
        migrations.AddField(
            model_name='commentongoal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Goal'),
        ),
    ]
