# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0004_auto_20180407_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 13, 37, 13, 836308)),
        ),
        migrations.AddField(
            model_name='user',
            name='pic_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentongoal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 13, 37, 13, 839939)),
        ),
        migrations.AlterField(
            model_name='commentonprogress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 13, 37, 13, 841061)),
        ),
        migrations.AlterField(
            model_name='commentonproject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 13, 37, 13, 840489)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 13, 37, 13, 837440)),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 13, 37, 13, 839389)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 13, 37, 13, 838517)),
        ),
    ]
