# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 15:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0005_auto_20180407_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='commentongoal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 18, 3, 458338)),
        ),
        migrations.AlterField(
            model_name='commentonprogress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 18, 3, 459590)),
        ),
        migrations.AlterField(
            model_name='commentonproject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 18, 3, 458926)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 18, 3, 454365)),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 18, 3, 457804)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 18, 3, 457192)),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 18, 3, 453204)),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfollowing',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Project'),
        ),
        migrations.AddField(
            model_name='projectfollowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalfollowing',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Goal'),
        ),
        migrations.AddField(
            model_name='goalfollowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
