# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0007_auto_20180407_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='confidentiality',
        ),
        migrations.AddField(
            model_name='project',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commentongoal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 48, 9, 657107)),
        ),
        migrations.AlterField(
            model_name='commentonprogress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 48, 9, 658481)),
        ),
        migrations.AlterField(
            model_name='commentonproject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 48, 9, 657843)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 48, 9, 653021)),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 48, 9, 656536)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 48, 9, 655883)),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 15, 48, 9, 651896)),
        ),
    ]
